name: Build for Nintendo Switch using CMake provided by devkitPro
on:
  pull_request:
  push:
  release:
    types: published
jobs:
  build-nintendo-switch:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    steps:
      - uses: actions/checkout@v2
      - name: "Build files"
        run: |
          /opt/devkitpro/portlibs/switch/bin/aarch64-none-elf-cmake -S. -Bbuild .. -DLIBRW_PLATFORM=GL3 -DLIBRW_GL3_GFXLIB=GLFW -DLIBRW_INSTALL=True
          cmake --build build --parallel
      - name: "Create binary package (cpack)"
        working-directory: ./build
        run: |
          cpack
      - name: "Archive binary package (github artifacts)"
        uses: actions/upload-artifact@v2
        with:
          name: "switch-gl3"
          path: build/*.tar.xz
          if-no-files-found: error
